### ISSUE TITLE
Rename goAsync keyword

### ISSUE THREAD

**Issue by Alogani** [Alogani/NimGo#18]
Because the library won't be strictly async, the keyword named `goAsync might not be appropriate ?

Here are some propositions:
- go
- goTask
- goAsync
- goNim
- launch
- startTask
- coSpawn

**Comment by hamidb80** [comment]
vote for `go` and `lunch`

**Comment by Alogani** [comment]
you mean `launch`? 😀

**Comment by hamidb80** [comment]
> you mean `launch`? 😀

sorry, yes `launch` 🚀

**Comment by hamidb80** [comment]
for waiting I suggest `stall` or `standby`. but normal `wait` is good

**Comment by Alogani** [comment]
I think `wait` is explicit and good. Strong typing is enough to avoid confusion if `wait`is also used with other APIs.

I'm still indecisive for the  `spawn` keyword. Maybe simply `go` -> simple, concise, explicit, pretty (But not very original^^), I will make my choice in few weeks at most.

Thanks for the suggestions :-)

**Comment by Alogani** [comment]
After some time to think about it, `go` might still be the best keyword. It is short, coherent with other names and easy to rememberand to the hear. Even if there are some drawbacks: very short so difficult to see inside code (no highlighting) and "stealing" the keyword from Golang.

This change will be acted in v0.0.9 release
