### ISSUE TITLE
Testing if NimGo test suite pass in windows

### ISSUE THREAD

**Issue by Alogani** [Alogani/NimGo#19]
If you have time, don't hesitate to run the test suites and the bench on windows with NimGo and tell me what are the errors messages.

If you know how and it is possible, you can also tell me how to add a windows github hosted runner

Any proposition of fix are also welcome ;-)

**Comment by hamidb80** [comment]
```
PS C:\Users\HamidB80\Documents\programming\NimGo> nimble test
  Verifying dependencies for nimgo@0.0.6
  Compiling C:\Users\HamidB80\Documents\programming\NimGo\tests\tcoroutines (from package nimgo) using c backend
C:\Users\HamidB80\Documents\programming\NimGo\src\nimgo\coroutines.nim(23, 14) Warning: Completly untested on windows. If I made a mistake the program will just early crash or won't compile [User]
C:\Users\HamidB80\Documents\programming\NimGo\src\nimgo\coroutines.nim(239, 58) Error: type mismatch
Expression: mergeStackTraceEntries(coroAddr)
  [1] coroAddr: pointer

Expected one of (first mismatch at [position]):
[1] proc mergeStackTraceEntries(coroPtr: ptr CoroutineObj): seq[StackTraceEntry]

       Tip: 2 messages have been suppressed, use --verbose to show them.
tools.nim(36)            doCmd

    Error:  Execution failed with exit code 1
        ... Command: C:\Users\HamidB80\.nimble\bin\nim.exe c --noNimblePath -d:NimblePkgVersion=0.0.6 --hints:off -r --path:. C:\Users\HamidB80\Documents\programming\NimGo\tests\tcoroutines
```

**Comment by Alogani** [comment]
Oops, I'm sorry, I thought I had better checked types. My bad

I have a big refactor on this file ongoing. I will merge it and create a new release in few days.

Maybe I will take time this weekend to install have a windows virtual machine on my pc (to not sollicitate you too much) and ensure it works.

**Comment by Alogani** [comment]
Unfortunatly, I naively thought that std/selectors was working with windows on files and other I/O. So there are still way to go before making it work on windows.

You can see here the advancement : https://github.com/Alogani/NimGo/discussions/26

For now, I close this issue because its goal was to make at least nimgo/coroutines works.
