### ISSUE TITLE
Convert 4-space indent to 2-space indent

### ISSUE THREAD

**Issue by Alogani** [Alogani/NimGo#22]
Although I highly prefer four spaces ident, this is the norm in Nim and it will facilitate contributions. I have modified my VsCodium settings to help me see them better.

**Comment by hamidb80** [comment]
Because the code written line after line with almost no empty line in between, IMAO convert it to 2-spaced makes the code _less readable_

I'm happy with the indentation size

**Comment by Alogani** [comment]
I personally dislike 2-space indent, but I have ambitions for this project to be one of Nim's key library. Unfortunatly Nim choose to have 2-space indent.

Having two space indent will make life easier for contributors that are used to it (like @Araq, who will certainly help for this project from time to time).

So i think I'm commited to this !
